name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify_plugin:
    name: Verify plugin
    uses: ./.github/workflows/_reusable-verify-plugin.yml

  analyze_code:
    name: Analyze code
    needs: verify_plugin
    uses: ./.github/workflows/_reusable-analyze-code.yml

  test_code:
    name: Test code and collect coverage
    needs: analyze_code
    uses: ./.github/workflows/_reusable-test-code.yml
